spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022221249?createDatabaseIfNotExist=true'
    username: 2022221249
    password: 2022221249
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'


my:
  secretkey: R28K42ZEg